services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: appuser
      RABBITMQ_DEFAULT_PASS: apppass
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq-service/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq-service/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s   
      retries: 12

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - RABBITMQ_URL=amqp://appuser:apppass@rabbitmq:5672/
    # env_file:
    #   - ./order-service/.env
    networks:
      - app-network
    # depends_on:
    #   rabbitmq:
    #     condition: service_healthy

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "3001:3001"
    environment:
      - RABBITMQ_URL=amqp://appuser:apppass@rabbitmq:5672
    # env_file:
    #   - ./inventory-service/.env
    networks:
      - app-network
    # depends_on:
    #   rabbitmq:
    #     condition: service_healthy

volumes:
  rabbitmq_data:

networks:
  app-network:
    name: hackathon-net
    driver: bridge
